# Generated by Django 6.0.6 on 2026-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description (UZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords (UZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title (UZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.IntegerField(default=12, verbose_name='Гарантия (месяцев)'),
        ),
    ]
