# Generated by Django 6.0.6 on 2026-06-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_slug_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Введите прямую ссылку на изображение (например, с imgbb.com, telegram или другого фотохостинга).', max_length=1000, null=True, verbose_name='Изображение (ссылка)'),
        ),
    ]
