# Generated by Django 6.0.6 on 2026-06-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Выберите изображение с вашего компьютера. Оно автоматически загрузится в постоянное облачное хранилище.', null=True, upload_to='temp_products/', verbose_name='Изображение (загрузить с ПК)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Ссылка на изображение. Заполняется автоматически при загрузке файла с ПК, либо можно указать ссылку вручную.', max_length=1000, null=True, verbose_name='Изображение (ссылка)'),
        ),
    ]
