# Generated by Django 6.0.6 on 2026-06-24 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_image_file_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, help_text='Заполняется автоматически при загрузке с ПК, либо укажите ссылку вручную.', max_length=1000, null=True, verbose_name='Ссылка на изображение')),
                ('image_file', models.ImageField(blank=True, help_text='Выберите файл изображения с вашего устройства.', null=True, upload_to='temp_products/', verbose_name='Загрузить файл с ПК')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_rel', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
