# Generated by Django 6.0.6 on 2026-06-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_code',
            field=models.CharField(blank=True, help_text='Например: #0000FF, #000000', max_length=7, null=True, verbose_name='Код цвета (HEX)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, help_text='Например: Синий, Черный', max_length=100, null=True, verbose_name='Название цвета'),
        ),
    ]
