# Generated by Django 6.0.6 on 2026-06-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, help_text='Ссылка на изображение. Заполняется автоматически при загрузке файла с ПК, либо можно указать ссылку вручную.', null=True, verbose_name='Изображение (ссылка)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.TextField(blank=True, help_text='Заполняется автоматически при загрузке с ПК, либо укажите ссылку вручную.', null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
