# Generated by Django 6.0.6 on 2026-06-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Выводить в секции Популярные товары на главной странице.', verbose_name='Популярный (на главной)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Показывать зеленый бейдж NEW.', verbose_name='Новинка (NEW)'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для отображения скидки. Если заполнена только одна валюта, вторая рассчитается по курсу.', max_digits=12, null=True, verbose_name='Старая цена (UZS)'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для отображения скидки в $. Рассчитается автоматически при указании UZS.', max_digits=12, null=True, verbose_name='Старая цена (USD)'),
        ),
    ]
