# Generated by Django 6.0.6 on 2026-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_is_featured_product_is_new_product_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_weekly_offer',
            field=models.BooleanField(default=False, help_text='Показывать в специальном блоке предложений недели на главной.', verbose_name='Предложение недели'),
        ),
    ]
